[tox]
envlist = test, makes

[testenv:  test]
allowlist_externals = rm
basepython = python
deps =
    cookiecutter
    coverage
    pytest
commands =
    rm -rf {temp_dir}/pypackage-basic
    cookiecutter . --no-input -o {temp_dir}
    python -m pip install -e {temp_dir}/pypackage-basic[dev]
    python -m pytest {temp_dir}/pypackage-basic/tests
    python -m coverage run --source {temp_dir}/pypackage-basic/pypackage_basic -m pytest -s {temp_dir}/pypackage-basic/tests
    python -m coverage report --show-missing --fail-under=100

[testenv:  makes]
allowlist_externals = make
basepython = python
changedir = {temp_dir}/pypackage-basic/
deps =
    cookiecutter
commands =
    python -m pip install -e {temp_dir}/pypackage-basic[dev]
    make lint
    make dist
    make coverage
    make test
    make clean
