[tox]
envlist = py310, py311, py312, py313, flake8, coverage

[testenv:flake8]
basepython = python
deps = flake8
commands = flake8 {{ cookiecutter.project_slug }}

[testenv]
setenv =
    PYTHONPATH = {toxinidir}
deps =
    -e .[dev]
commands =
    python -m pytest --basetemp={envtmpdir}

[testenv:coverage]
basepython = python
deps =
    -e .[dev]
commands =
    python -m coverage run --source {{ cookiecutter.project_slug }} -m pytest
    python -m coverage report --show-missing --fail-under=95
