[tox]
envlist = py310, py311, py312, py313, flake8, coverage

[testenv:flake8]
basepython = python
deps = flake8
commands = flake8 {{ cookiecutter.project_slug }}

[testenv]
setenv =
    PYTHONPATH = {toxinidir}
deps =
    -r{toxinidir}/requirements.txt
commands =
    python -m pip install --upgrade pip setuptools wheel
    pip install coverage pytest
    py.test --basetemp={envtmpdir}

[testenv:coverage]
basepython = python
deps =
    -r{toxinidir}/requirements.txt
    coverage
    pytest
commands =
    coverage run --source {{ cookiecutter.project_slug }} -m pytest
    coverage report --show-missing --fail-under=95
