name: Test

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  test:
    runs-on: {{ '${{' }} matrix.os {{ '}}' }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: {{ '${{' }} matrix.python-version {{ '}}' }}
          architecture: "x64"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install coverage pytest
          pip install -e .
      - name: PyTest
        run: |
          coverage run --source {{cookiecutter.project_slug}} -m pytest
          pytest tests/
      - name: Coverage
        env:
          GITHUB_TOKEN: {{ '${{' }} secrets.github_token {{ '}}' }}
          COVERALLS_FLAG_NAME: {{ '${{' }} matrix.python-version {{ '}}' }}
          COVERALLS_PARALLEL: true
        if: (! contains(matrix.python-version, 'pypy'))
        run: |
          coverage report --show-missing --fail-under=100
          pip install coveralls
          coverage report --show-missing
          coveralls --service=github

  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          github-token: {{ '${{' }} secrets.github_token {{ '}}' }}
          parallel-finished: true


